<a href="https://colab.research.google.com/github/Anannya-Vyas/EXPLORATORY-DATA-ANALYSIS/blob/main/Handling_Missing_Values.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import display

In [15]:
import pandas as pd
# https://github.com/Anannya-Vyas/datasets/blob/6f9a1d1320a85a5759ed639ccde75a342a5fdf47/Churn_Modelling.xlsx

url = "https://raw.githubusercontent.com/Anannya-Vyas/datasets/main/Churn_Modelling.xlsx"

df = pd.read_excel(url)

In [ ]:
df= pd.read_excel("Churn_Modelling.csv.xlsx")

In [ ]:
# Method one of checking for null values
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          9999 non-null   object
 3   CreditScore      9991 non-null   float64
 4   Geography        10000 non-null  object
 5   Gender           9995 non-null   object
 6   Age              9999 non-null   float64
 7   Tenure           10000 non-null  int64
 8   Balance          9999 non-null   float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        9999 non-null   float64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           9997 non-null   float64
dtypes: float64(6), int64(5), object(3)
memory usage: 1.1+ MB

insights

There is one null value in surname

 9 null values in credit score


 five null values in gender

 one null value in age

 one null value in balance

 1 null in has credit card

 three null values in excited

In [ ]:
# Method two for checking null values
print(df.isnull().sum())

RowNumber          0
CustomerId         0
Surname            1
CreditScore        9
Geography          0
Gender             5
Age                1
Tenure             0
Balance            1
NumOfProducts      0
HasCrCard          1
IsActiveMember     0
EstimatedSalary    0
Exited             3
dtype: int64

In [ ]:
display(df.isnull().sum())

RowNumber          0
CustomerId         0
Surname            1
CreditScore        9
Geography          0
Gender             5
Age                1
Tenure             0
Balance            1
NumOfProducts      0
HasCrCard          1
IsActiveMember     0
EstimatedSalary    0
Exited             3
dtype: int64

In [ ]:
display(df)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619.0,France,Female,42.0,2,0.00,1,1.0,1,101348.88,1.0
1,2,15647311,Hill,608.0,Spain,Female,41.0,1,83807.86,1,0.0,1,112542.58,0.0
2,3,15619304,Onio,502.0,France,Female,42.0,8,159660.80,3,1.0,0,113931.57,1.0
3,4,15701354,Boni,699.0,France,Female,39.0,1,0.00,2,0.0,0,93826.63,0.0
4,5,15737888,Mitchell,850.0,Spain,Female,43.0,2,125510.82,1,1.0,1,79084.10,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771.0,France,Male,39.0,5,0.00,2,1.0,0,96270.64,0.0
9996,9997,15569892,Johnstone,516.0,France,Male,35.0,10,57369.61,1,1.0,1,101699.77,0.0
9997,9998,15584532,Liu,709.0,France,Female,36.0,7,0.00,1,0.0,1,42085.58,1.0
9998,9999,15682355,Sabbatini,772.0,Germany,Male,42.0,3,75075.31,2,1.0,0,92888.52,1.0
9999,10000,15628319,Walker,792.0,France,Female,28.0,4,130142.79,1,1.0,0,38190.78,0.0

📌 Why axis works like this?

> axis=0 → move vertically (row-wise)

> axis=1 → move horizontally (column-wise)

In [ ]:
# Handling missing values
# METHOD 1: DELETTE ROWS AND COLUMNS
updated_df= df.dropna(axis=0)
print(df.shape)
print(updated_df.shape)
updated_df.info()
# And if you don't define any axis That means 👉
# it removes rows that contain missing (NaN) values.

(10000, 14)
(9983, 14)
<class 'pandas.core.frame.DataFrame'>
Index: 9983 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        9983 non-null   int64
 1   CustomerId       9983 non-null   int64
 2   Surname          9983 non-null   object
 3   CreditScore      9983 non-null   float64
 4   Geography        9983 non-null   object
 5   Gender           9983 non-null   object
 6   Age              9983 non-null   float64
 7   Tenure           9983 non-null   int64
 8   Balance          9983 non-null   float64
 9   NumOfProducts    9983 non-null   int64
 10  HasCrCard        9983 non-null   float64
 11  IsActiveMember   9983 non-null   int64
 12  EstimatedSalary  9983 non-null   float64
 13  Exited           9983 non-null   float64
dtypes: float64(6), int64(5), object(3)
memory usage: 1.1+ MB

In [ ]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            1
CreditScore        9
Geography          0
Gender             5
Age                1
Tenure             0
Balance            1
NumOfProducts      0
HasCrCard          1
IsActiveMember     0
EstimatedSalary    0
Exited             3
dtype: int64

In [ ]:
# METHOD 2 Replacing with mean median and mode
# We can use mode for gender and surname
# we can use median for credit score
# We can use mean for and balance
df=pd.read_excel("Churn_Modelling.csv.xlsx")
updated_df= df
print(updated_df["Surname"].mode()) # we can use this but better practice is to drop it

df.info()

0    Smith
Name: Surname, dtype: object
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          9999 non-null   object
 3   CreditScore      9991 non-null   float64
 4   Geography        10000 non-null  object
 5   Gender           9995 non-null   object
 6   Age              9999 non-null   float64
 7   Tenure           10000 non-null  int64
 8   Balance          9999 non-null   float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        9999 non-null   float64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           9997 non-null   float64
dtypes: float64(6), int64(5), object(3)
memory usage: 1.1+ MB

In [ ]:
updated_df.dropna(subset=["Surname"], inplace=True)

In [ ]:

mode = updated_df["Exited"].mode()[0]
print(mode)
print('\n')

updated_df.fillna({"Exited": mode},inplace=True)

updated_df.info()

0.0


<class 'pandas.core.frame.DataFrame'>
Index: 9999 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        9999 non-null   int64
 1   CustomerId       9999 non-null   int64
 2   Surname          9999 non-null   object
 3   CreditScore      9990 non-null   float64
 4   Geography        9999 non-null   object
 5   Gender           9994 non-null   object
 6   Age              9998 non-null   float64
 7   Tenure           9999 non-null   int64
 8   Balance          9998 non-null   float64
 9   NumOfProducts    9999 non-null   int64
 10  HasCrCard        9998 non-null   float64
 11  IsActiveMember   9999 non-null   int64
 12  EstimatedSalary  9999 non-null   float64
 13  Exited           9999 non-null   float64
dtypes: float64(6), int64(5), object(3)
memory usage: 1.1+ MB

In [ ]:
median = updated_df["CreditScore"].median
print(median ,"\n")
updated_df.fillna({"CreditScore": median}, inplace=True)
updated_df.info()

<bound method Series.median of 0       619.0
1       608.0
2       502.0
3       699.0
4       850.0
        ...
9995    771.0
9996    516.0
9997    709.0
9998    772.0
9999    792.0
Name: CreditScore, Length: 9999, dtype: object>

<class 'pandas.core.frame.DataFrame'>
Index: 9999 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        9999 non-null   int64
 1   CustomerId       9999 non-null   int64
 2   Surname          9999 non-null   object
 3   CreditScore      9999 non-null   object
 4   Geography        9999 non-null   object
 5   Gender           9994 non-null   object
 6   Age              9998 non-null   float64
 7   Tenure           9999 non-null   int64
 8   Balance          9998 non-null   float64
 9   NumOfProducts    9999 non-null   int64
 10  HasCrCard        9998 non-null   float64
 11  IsActiveMember   9999 non-null   int64
 12  EstimatedSalary  9999 non-null   float64
 13  Exited           9999 non-null   float64
dtypes: float64(5), int64(5), object(4)
memory usage: 1.1+ MB

In [ ]:
mode =updated_df["Gender"].mode
print(mode,"\n")
updated_df.fillna({"Gender": mode}, inplace=True)
updated_df.info()

<bound method Series.mode of 0       Female
1       Female
2       Female
3       Female
4       Female
         ...
9995      Male
9996      Male
9997    Female
9998      Male
9999    Female
Name: Gender, Length: 9999, dtype: object>

<class 'pandas.core.frame.DataFrame'>
Index: 9999 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        9999 non-null   int64
 1   CustomerId       9999 non-null   int64
 2   Surname          9999 non-null   object
 3   CreditScore      9999 non-null   object
 4   Geography        9999 non-null   object
 5   Gender           9999 non-null   object
 6   Age              9998 non-null   float64
 7   Tenure           9999 non-null   int64
 8   Balance          9998 non-null   float64
 9   NumOfProducts    9999 non-null   int64
 10  HasCrCard        9998 non-null   float64
 11  IsActiveMember   9999 non-null   int64
 12  EstimatedSalary  9999 non-null   float64
 13  Exited           9999 non-null   float64
dtypes: float64(5), int64(5), object(4)
memory usage: 1.1+ MB

In [ ]:
mean =updated_df["Age"].mean
updated_df.fillna({"Age":mean}, inplace=True)
updated_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9999 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        9999 non-null   int64
 1   CustomerId       9999 non-null   int64
 2   Surname          9999 non-null   object
 3   CreditScore      9999 non-null   object
 4   Geography        9999 non-null   object
 5   Gender           9999 non-null   object
 6   Age              9999 non-null   object
 7   Tenure           9999 non-null   int64
 8   Balance          9998 non-null   float64
 9   NumOfProducts    9999 non-null   int64
 10  HasCrCard        9998 non-null   float64
 11  IsActiveMember   9999 non-null   int64
 12  EstimatedSalary  9999 non-null   float64
 13  Exited           9999 non-null   float64
dtypes: float64(4), int64(5), object(5)
memory usage: 1.1+ MB

In [ ]:
mean2 =updated_df["Balance"].mean
updated_df.fillna({"Balance":mean2}, inplace=True)
updated_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9999 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        9999 non-null   int64
 1   CustomerId       9999 non-null   int64
 2   Surname          9999 non-null   object
 3   CreditScore      9999 non-null   object
 4   Geography        9999 non-null   object
 5   Gender           9999 non-null   object
 6   Age              9999 non-null   object
 7   Tenure           9999 non-null   int64
 8   Balance          9999 non-null   object
 9   NumOfProducts    9999 non-null   int64
 10  HasCrCard        9998 non-null   float64
 11  IsActiveMember   9999 non-null   int64
 12  EstimatedSalary  9999 non-null   float64
 13  Exited           9999 non-null   float64
dtypes: float64(3), int64(5), object(6)
memory usage: 1.1+ MB

In [ ]:
mode = updated_df["HasCrCard"].mode()[0]
print(mode)
updated_df.fillna({"HasCrCard": mode}, inplace=True)
updated_df.info()

1.0
<class 'pandas.core.frame.DataFrame'>
Index: 9999 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        9999 non-null   int64
 1   CustomerId       9999 non-null   int64
 2   Surname          9999 non-null   object
 3   CreditScore      9999 non-null   object
 4   Geography        9999 non-null   object
 5   Gender           9999 non-null   object
 6   Age              9999 non-null   object
 7   Tenure           9999 non-null   int64
 8   Balance          9999 non-null   object
 9   NumOfProducts    9999 non-null   int64
 10  HasCrCard        9999 non-null   float64
 11  IsActiveMember   9999 non-null   int64
 12  EstimatedSalary  9999 non-null   float64
 13  Exited           9999 non-null   float64
dtypes: float64(3), int64(5), object(6)
memory usage: 1.1+ MB

In [ ]:
# final check
print(updated_df.isnull().sum())

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

Forward Fill (ffill)
👉 Concept:

Replace missing value with the previous valid value.

In [ ]:
df=pd.read_excel("Churn_Modelling.csv.xlsx")
print(df.isnull().sum())
df.fillna(method="ffill", inplace=True)
print(df.isnull().sum())

RowNumber          0
CustomerId         0
Surname            1
CreditScore        9
Geography          0
Gender             5
Age                1
Tenure             0
Balance            1
NumOfProducts      0
HasCrCard          1
IsActiveMember     0
EstimatedSalary    0
Exited             3
dtype: int64
RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

/tmp/ipykernel_1155/862743359.py:3: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill", inplace=True)

 Backward Fill (bfill)
👉 Concept:

Replace missing value with the next valid value.

In [ ]:
df=pd.read_excel("Churn_Modelling.csv.xlsx")
print(df.isnull().sum())
df.fillna(method="bfill", inplace=True)
print(df.isnull().sum())

RowNumber          0
CustomerId         0
Surname            1
CreditScore        9
Geography          0
Gender             5
Age                1
Tenure             0
Balance            1
NumOfProducts      0
HasCrCard          1
IsActiveMember     0
EstimatedSalary    0
Exited             3
dtype: int64
RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

/tmp/ipykernel_1155/991446784.py:3: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="bfill", inplace=True)

*for each column *

In [11]:
import pandas as pd

url = "https://raw.githubusercontent.com/Anannya-Vyas/datasets/main/Churn_Modelling.xlsx"

ndf = pd.read_excel(url)
print(ndf.isnull().sum())



# backward fill only for Surname column
ndf["Surname"] = ndf["Surname"].bfill()
print(ndf.isnull().sum())

RowNumber          0
CustomerId         0
Surname            1
CreditScore        9
Geography          0
Gender             5
Age                1
Tenure             0
Balance            1
NumOfProducts      0
HasCrCard          1
IsActiveMember     0
EstimatedSalary    0
Exited             3
dtype: int64
RowNumber          0
CustomerId         0
Surname            0
CreditScore        9
Geography          0
Gender             5
Age                1
Tenure             0
Balance            1
NumOfProducts      0
HasCrCard          1
IsActiveMember     0
EstimatedSalary    0
Exited             3
dtype: int64

In [12]:
ndf.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619.0,France,Female,42.0,2,0.00,1,1.0,1,101348.88,1.0
1,2,15647311,Hill,608.0,Spain,Female,41.0,1,83807.86,1,0.0,1,112542.58,0.0
2,3,15619304,Onio,502.0,France,Female,42.0,8,159660.80,3,1.0,0,113931.57,1.0
3,4,15701354,Boni,699.0,France,Female,39.0,1,0.00,2,0.0,0,93826.63,0.0
4,5,15737888,Mitchell,850.0,Spain,Female,43.0,2,125510.82,1,1.0,1,79084.10,0.0

In [13]:
# forward fill only for Age column
ndf["Age"] = ndf["Age"].ffill()
print(ndf.isnull().sum())

RowNumber          0
CustomerId         0
Surname            0
CreditScore        9
Geography          0
Gender             5
Age                0
Tenure             0
Balance            1
NumOfProducts      0
HasCrCard          1
IsActiveMember     0
EstimatedSalary    0
Exited             3
dtype: int64

In [14]:
display(ndf)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619.0,France,Female,42.0,2,0.00,1,1.0,1,101348.88,1.0
1,2,15647311,Hill,608.0,Spain,Female,41.0,1,83807.86,1,0.0,1,112542.58,0.0
2,3,15619304,Onio,502.0,France,Female,42.0,8,159660.80,3,1.0,0,113931.57,1.0
3,4,15701354,Boni,699.0,France,Female,39.0,1,0.00,2,0.0,0,93826.63,0.0
4,5,15737888,Mitchell,850.0,Spain,Female,43.0,2,125510.82,1,1.0,1,79084.10,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771.0,France,Male,39.0,5,0.00,2,1.0,0,96270.64,0.0
9996,9997,15569892,Johnstone,516.0,France,Male,35.0,10,57369.61,1,1.0,1,101699.77,0.0
9997,9998,15584532,Liu,709.0,France,Female,36.0,7,0.00,1,0.0,1,42085.58,1.0
9998,9999,15682355,Sabbatini,772.0,Germany,Male,42.0,3,75075.31,2,1.0,0,92888.52,1.0
9999,10000,15628319,Walker,792.0,France,Female,28.0,4,130142.79,1,1.0,0,38190.78,0.0